name: 'upload-fleetconnect'
description: 'This action upload artifact to FleetConnect as a package version that can be deployed.'
author: 'benjamin.tucker@kontron.com'

inputs:
  fleetconnect_client_id:
    description: 'FleetConnect Client ID credential'
    required: true

  fleetconnect_client_secret:
    description: 'FleetConnect Client Secret credential'
    required: true

  fleetconnect_token_endpoint:
    description: 'FleetConnect Token Endpoint'
    required: true

  source_dir:
    description: 'The local directory (or file) you wish to upload. Directories are uploaded as FleetConnect Tar Package files'
    required: true

  package_name:
    description: 'The name of the package to create'
    required: true

  package_category:
    description: 'The category of the package to create'
    required: true
    default: `artifact`

  package_description:
    description: 'The a description for the package'
    required: false

outputs:
  package_id:
    description: 'The package ID'

  package_version_id:
    description: 'The package version ID'

runs:
  using: node20
  main: dist/index.js
